version: 2

sources:
  - name: my_new_project
    database: raw
    schema: retail_db
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: departments
      - name: categories

  - name: retailer
    database: raw
    schema: retailer
    tables: 
      - name: customers
      - name: orders
      - name: products
      - name: order_items
      - name: departments
      - name: categories

      